index:
  path: /{page}
  defaults: { _controller: ReviewStarBookBundle:Page:list, page: 1 }
  requirements:
    page: \d+

rs_book_create:
  path: /book/create
  defaults: { _controller: ReviewStarBookBundle:Book:create }

rs_book_view:
  path: /book/{id}
  defaults: { _controller: ReviewStarBookBundle:Book:view }
  requirements:
    id: \d+

rs_book_edit:
  path: /book/edit/{id}
  defaults: { _controller: ReviewStarBookBundle:Book:edit }
  requirements:
    id: \d+

rs_book_delete:
  path: /book/delete/{id}
  defaults: { _controller: ReviewStarBookBundle:Book:delete }
  requirements:
    id: \d+

rs_review_create:
  path: /book/{bookId}/review/create
  defaults: { _controller: ReviewStarBookBundle:Review:create }
  requirements:
    bookId: \d+

rs_review_edit:
  path: /book/{bookId}/review/{id}
  defaults: { _controller: ReviewStarBookBundle:Review:edit }
  requirements:
    id: \d+
    bookId: \d+

rs_review_delete:
  path: delete/review/{id}
  defaults: { _controller: ReviewStarBookBundle:Review:delete }
  requirements:
    id: \d+
    bookId: \d+

rs_user_login:
  path:     /login
  defaults: { _controller: FOSUserBundle:Security:login }

rs_user_logout:
  path:     /logout
  defaults: { _controller: FOSUserBundle:Security:logout }

rs_user_register:
  path: /register
  defaults: { _controller: FOSUserBundle:Registration:register }
