<?php

namespace BookBundle\Repository;

/**
 * ReviewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRepository extends \Doctrine\ORM\EntityRepository
{
    public function getReviewsByUser($userId)
    {
        $dql = $this->createQueryBuilder("review")->orderBy('review.created', 'DESC')->where("review.user = " . $userId);
        $query = $dql->getQuery();
        return $query->getResult();
    }

    public function getReviewsByBook($bookId)
    {
        $dql = $this->createQueryBuilder("review")->where("review.book = " . $bookId);
        $query = $dql->getQuery();
        return $query->getResult();
    }
}
