rs_user_login:
  path:     /login
  defaults: { _controller: FOSUserBundle:Security:login }

rs_user_logout:
  path:     /logout
  defaults: { _controller: FOSUserBundle:Security:logout }

rs_user_register:
  path: /register
  defaults: { _controller: FOSUserBundle:Registration:register }
