index:
  path: /{page}
  defaults: { _controller: BookBundle:Page:list, page: 1 }
  requirements:
    page: \d+

rs_book_create:
  path: /book/create
  defaults: { _controller: BookBundle:Book:create }

rs_book_view:
  path: /book/{id}
  defaults: { _controller: BookBundle:Book:view }
  requirements:
    id: \d+

rs_book_edit:
  path: /book/edit/{id}
  defaults: { _controller: BookBundle:Book:edit }
  requirements:
    id: \d+

rs_book_delete:
  path: /book/delete/{id}
  defaults: { _controller: BookBundle:Book:delete }
  requirements:
    id: \d+

rs_book_search:
  path: /search
  defaults: { _controller: BookBundle:Page:search }

rs_handle_search:
  path: /results
  defaults: { _controller: BookBundle:Page:handleSearch }

rs_review_create:
  path: /book/{bookId}/review/create
  defaults: { _controller: BookBundle:Review:create }
  requirements:
    bookId: \d+

rs_review_edit:
  path: /book/{bookId}/review/{id}
  defaults: { _controller: BookBundle:Review:edit }
  requirements:
    id: \d+
    bookId: \d+

rs_review_delete:
  path: delete/review/{id}
  defaults: { _controller: BookBundle:Review:delete }
  requirements:
    id: \d+
    bookId: \d+

rs_user_catalog:
  path: /users
  defaults: { _controller: BookBundle:Page:userIndex }

rs_user_edit:
  path: /users/edit/{id}
  defaults: { _controller: BookBundle:Page:userEdit }
  requirements:
    id: \d+

rs_user_view:
  path: /users/view/{id}
  defaults: { _controller: BookBundle:Page:userView }
  requirements:
    id: \d+

rs_user_login:
  path:     /login
  defaults: { _controller: FOSUserBundle:Security:login }

rs_user_logout:
  path:     /logout
  defaults: { _controller: FOSUserBundle:Security:logout }

rs_user_register:
  path: /register
  defaults: { _controller: FOSUserBundle:Registration:register }


rs_joindin_events_all:
  path: /events
  defaults: { _controller: BookBundle:Joindin:events }

rs_joindin_event:
  path: /events/{index}
  defaults: { _controller: BookBundle:Joindin:event }
  requirements:
    index: \d+

rs_joindin_event_talks:
  path: /events/{index}/talks/
  defaults: { _controller: BookBundle:Joindin:talks }
  requirements:
    index: \d+