blogger_about:
  path:       /about
  defaults: { _controller: BloggerBlogBundle:Page:about }
  requirements:
    _method: GET

blogger_login:
  path:     /login
  defaults: { _controller: FOSUserBundle:Security:login }

blogger_logout:
  path:     /logout
  defaults: { _controller: FOSUserBundle:Security:logout }

index:
    path:     /
    defaults: { _controller: BloggerBlogBundle:Page:index }
