blogger_about:
  path:       /about
  defaults: { _controller: BloggerBlogBundle:Page:about }
  requirements:
    _method: GET

#index:
#    path:     /
#    defaults: { _controller: BloggerBlogBundle:Page:index }

blogger_post_view:
    path:     /view/{id}
    defaults: { _controller: BloggerBlogBundle:Post:view }
    requirements:
      id: \d+

blogger_post_create:
    path:     /create
    defaults: { _controller: BloggerBlogBundle:Post:create }

blogger_post_edit:
    path:     /edit/{id}
    defaults: { _controller: BloggerBlogBundle:Post:edit }
    requirements:
      id: \d+

blogger_post_delete:
    path:     /delete/{id}
    defaults: { _controller: BloggerBlogBundle:Post:delete }
    requirements:
      id: \d+
