<?php

namespace ReviewStar\BookBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function countBooks()
    {
        $qb = $this->createQueryBuilder('book');
        $qb->select('COUNT(book)');
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }

    public function getBooksByUser($userId)
    {
        $dql = $this->createQueryBuilder("book")->orderBy('book.created', 'DESC')->where("book.user = " . $userId);
        $query = $dql->getQuery();
        return $query->getResult();
    }

    public function getLatest($limit, $offset) {
        $queryBuilder = $this->createQueryBuilder('book');

        $queryBuilder
            ->orderBy('book.created', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }

    public function getPage($booksPerPage, $currentPage) {
        $offSet = ($currentPage - 1) * $booksPerPage;
        return $this->getLatest($booksPerPage, $offSet);
    }

    public function getBooksBySearch($string, $filter) {
        $dql = $this->createQueryBuilder("book")
            ->where($this->processFilterChoice($filter))
            ->setParameter('term', '%' . $string . '%');
        $query = $dql->getQuery();
        return $query->getResult();
    }

    public function processFilterChoice($filter) {
        switch($filter) {
            case 'author':
                return 'book.bookAuthor LIKE :term';
            case 'title':
                return 'book.bookTitle LIKE :term';
            case 'publisher':
                return 'book.bookPublisher LIKE :term';
            default:
                return 'book.bookTitle LIKE :term';
        }
    }
}
