<?php

namespace ReviewStar\BookBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
    public function countBooks()
    {
        $qb = $this->createQueryBuilder("book");
        $qb->select("COUNT(book)");
        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }

    public function getBooksByUser($userId)
    {
        $dql = $this->createQueryBuilder("book")->where("book.user_id = " . $userId);
        $dql->getQuery();
    }

    public function getLatest($limit, $offset) {
        $queryBuilder = $this->createQueryBuilder('book');

        $queryBuilder->orderBy('book.created', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults($limit);

        $query = $queryBuilder->getQuery();

        return $query->getResult();
    }
}
